function macros() {
#macro SECOND 60
#macro BOMB_TEXT_OFFSET_X 0
#macro BOMB_TEXT_OFFSET_Y 0
#macro DARK_GRAY $212121
#macro MEDIUM_GRAY $151414
#macro LIGHT_GRAY $363636
#macro BLACK_GRAY $0d0d0d
#macro COLOR_GREEN_BUTTON $12CE35
#macro COLOR_BLUEBERRY_BUTTON $181536
#macro KEYBOARD -1
#macro FADE_OFF_SPEED 0.02
#macro NN_DISCONNECT 0
#macro NN_LBY_CONNECTED 1
#macro NN_CHAT 2
#macro NN_LBY_REQUEST_SETTINGS 3
#macro NN_LBY_SEND_SETTINGS 4
#macro NN_LBY_PRESS_BEJ3 5
#macro NN_LBY_PRESS_CLASSIC 6
#macro NN_LBY_SKINS 7
#macro NN_LBY_TWIST 8
#macro NN_LBY_MATCHLESS 9
#macro NN_LBY_HYPERCUBES 10
#macro NN_LBY_MULTISWAP 11
#macro NN_LBY_GAMEMODE 12
#macro NN_LBY_GAMEMODE2 13
#macro NN_LBY_READY 14
#macro NN_MATCH_BOARD_SPAWN 15
#macro NN_MATCH_GEM_DEATH 16
#macro NN_MATCH_GEM_SPAWN 17
#macro NN_MATCH_GEM_SWAP 18
#macro NN_MATCH_DUALHYPE_MAKE_HYPE 19 //when a dual hype has happened, spawner will spawn a specific array of gems. Two will be hypes.
#macro NN_MATCH_GEM_POWER 20
#macro NN_MATCH_GEM_POWER_NEW 21
#macro NN_BACK_TO_LOBBY 22
#macro NN_MATCH_GEM_COMBO_SOUND 23
#macro NN_MATCH_BLAZING_SPEED_ON 24
#macro NN_MATCH_BLAZING_SPEED_OFF 25
#macro NN_POINTS_ADD 26
#macro NN_STYLE_ADD 27
#macro NN_MATCH_GEM_HYPER 28
#macro NN_MATCH_GEM_HYPER_NEW 29
#macro NN_MATCH_HYPE_SWAP 30
#macro NN_MATCH_HYPE_OFF 31
#macro NN_MATCH_GO 32
#macro NN_MATCH_TWIST_SWAP 33
#macro NN_MATCH_TIMEUP 34
#macro NN_MATCH_AHM_SPAWN 35
#macro NN_MATCH_AHM_SETSKIN 36
#macro NN_MATCH_AVALANCHE_END_TURN 37
#macro NN_MATCH_AVALANCHE_HIDDENMINUS 38 //subtract minus gems by spawning a gem
#macro NN_MATCH_AVALANCHE_GAMEOVER 39
#macro NN_MUSIC_DANGERON 40
#macro NN_MUSIC_DANGEROFF 41
#macro NN_SERVER_CHECK_VER 42
#macro NN_SERVER_GAME_SETTINGS 43
#macro NN_LBY_DEFENSE 44
#macro NN_MATCH_AVALANCHE_PASS 45
#macro NN_LBY_ULTRANOVAS 46
#macro NN_DISSALLOW_SPECTATORS 47
#macro NN_ALLOW_SPECTATORS 48
#macro NN_SERVER_REPLAY_STOP 49
#macro NN_MATCH_POWERUP_LOCK 50
#macro NN_MATCH_SEND_POINTS 51 //after a lightning/hypercube ends, we send the points that we got during that time
#macro NN_MATCH_INVERTED_OVER 52 //when inverted swap is over, send that info
#macro NN_SERVER_REPLAY_DATA 53 //when horizontal or vertical swap is over, send that info
#macro NN_MATCH_TUG_INFO 54
#macro NN_AMREADY 55
#macro NN_YOUARE_HOST 56
#macro NN_LBY_BLAZING 57
#macro NN_YOUARE_SPECTATOR 58
#macro NN_SPECTATOR_JOINED 59
#macro NN_SPECTATOR_DISCONNECT 60
#macro NN_MATCH_AMEXPLODE 61
#macro NN_SERVER_BYE 62
#macro GLOW_FADEOUT_FRAMES 10
#macro FLAME 1
#macro LIGHTNING 2
#macro NOVA 3
#macro SEPTA 4
#macro OCTA 5
#macro FRUIT 6






}
