with(obj_bombcontrol) event_user(1)
with(obj_coal_control) event_user(1)
with(obj_lock_control) event_user(1)
with(obj_skull_control) event_user(1)
with(obj_ice_lock_control) event_user(1)
with(obj_doom_control) event_user(1)