ds_list_clear(list_of_matches)
	ds_list_clear(list_of_bombs)
	ds_list_clear(list_of_coals)
	ds_list_clear(list_of_fruits)
	ds_list_clear(list_of_ice_locks)
	ds_list_clear(list_of_hiddengems)
	ds_list_clear(list_of_locks)
