instance_destroy(obj_tfj_special_main)
instance_destroy(obj_tfj_special_card_container)
instance_destroy(obj_tfj_special_reroll)
obj_tfj_ingame_special_button.cards=[]
obj_tfj_ingame_special_button.clickable=true

